disabled_rules: # rule to exclude from running
  - function_body_length
  - block_based_kvo
  - notification_center_detachment
opt_in_rules: # opt-in rules
  - empty_count
  - force_unwrapping
  - missing_docs
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - private_action
  - private_outlet
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - unavailable_function
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_collection_literal
identifier_name: # minimum identifier length
  min_length: 2
included:
  - ../Habanero/Classes
excluded:
  - Pods
